# Generated by Django 5.2.5 on 2025-08-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HangOut', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hangout_room',
            table='HangOut_Room',
        ),
    ]
