# Generated by Django 5.2.5 on 2025-08-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HangOut', '0003_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
