# Generated by Django 5.2.1 on 2025-08-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmallJobsHome', '0002_smalljobsuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smalljobsuser',
            name='username',
        ),
    ]
